matches:
  # Autotext untuk Sapaan
  - trigger: ";halo"
    replace: "Halo kak, selamat datang di Zasha. Ada yang bisa kami bantu?"

  # Autotext untuk Link Website
  - trigger: ";22"
    replace: "mohon ditunggu untuk replay suksesnya ya kak untuk produk tersebut sedang Padat sedang dalam penanganan pihak terkait 🙏🏻. "
  - trigger: ";23"
    replace: "Mohon maaf terkait kendalanya, perihal transaksi tersebut sedang dalam proses recon, mohon tunggu update transaksinya. terimakasih."
  - trigger: ";1"
    replace: "Hi kak, Dengan CS AEMITRA, ada yg bisa kita bantu ? "
  - trigger: ";2"
    replace: "Mohon maaf Transaksi sedang dalam proses dan sedang kami bantu, mohon tunggu ya kak. transaksi dalam proses tidak dapat kami batalkan/ sukseskan."
  - trigger: "12"
    replace: "* Maaf, Komplain, langsung sertakan nomornya, agar bisa langsung kami cek "
  - trigger: ";21"
    replace: "maaf untuk transakasi padat sedang kami bantu dan sudah kami followup ke bagian rekon data. mohon tunggu reply balasan , transaksi diatas mohon tunggu 😊🙏"
  - trigger: ";3"
    replace: "Baik Mohon tunggu, kita bantu cek ulang."
  - trigger: ";31"
    replace: "Mohon maaf transaksi dalam proses pengecekan tidak bisa di batalkan kak mohon tunggu update nya ya."
  - trigger: ";32"
    replace: "baik kak mohon tunggu sedang kami bantu cek ulang jika sudah update akan kami infokan kembali ya kakak, Transaksi tersebut sudah kita bantu teruskan ke bagian terkait kami. "
  - trigger: ";33"
    replace: "Mohon maaf terkait kendalanya, Transaksi tersebut sudah kita bantu  ReCo ke bagaian terkait kami, maaf terkait ketidak nyamananya."
  - trigger: ";24"
    replace: "Maaf Belum bisa kita  pastikan, kita bantu proses secepatnya, Terimakasih."
  - trigger: ";5"
    replace: "Apakah ada kendala kembali yang perlu kita bantu kaka ? "
  - trigger: ";51"
    replace: "Jika tidak ada, selamat bertransaksi kembali, kami sampaikan terimakasih."
  - trigger: ";52"
    replace: "Baik sama-sama, Semoga selalu di berikan kelancaran selalu usahanya, dan AEMITRA selalu di hati anda."
  - trigger: ";agen"
    replace: "ketik STOK KIRIM KE CENTER : ✅https://wa.me/6285311115235 LANCAR ✅"
  - trigger: ";as"
    replace: "ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ"
  - trigger: ";was"
    replace: "وَعَلَيْكُمُ السَّلاَمُ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ"
  - trigger: ";wa"
    replace: "...::: WHATSAPP CENTER AEMITRA :::...✅https://wa.me/6285311115235 LANCAR ✅ "
  # Autotext untuk Belajar Git
  - trigger: ";gitsave"
    replace: "git add . && git commit -m 'update' && git push origin main"

  # Tanggal otomatis
  - trigger: ";tgl"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"